apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - local-websecure
  routes:
    - match: Host(`argocd.ssl.local.vpineda.me`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    certResolver: wildcard-resolver
    domains:
      - main: "ssl.local.vpineda.me"
      - sans:
          - "*.ssl.local.vpineda.me"