apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-code-ingress
  namespace: home-assistant
spec:
  entryPoints:
    - local-websecure
  routes:
    - match: Host(`code.ssl.local.vpineda.me`)
      kind: Rule
      services:
        - name: home-assistant-codeserver
          port: 12321
  tls:
    certResolver: wildcard-resolver
    domains:
      - main: "ssl.local.vpineda.me"
      - sans:
          - "*.ssl.local.vpineda.me"