apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - local-websecure
  routes:
    - match: Host(`monitoring.ssl.local.vpineda.me`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
  tls:
    certResolver: wildcard-resolver
    domains:
      - main: "ssl.local.vpineda.me"
      - sans:
          - "*.ssl.local.vpineda.me"